"""The seed formulary: 40 common Indian outpatient drugs, hand-curated.

This is the PRIMARY deliverable of `puriyudha.formulary` -- not a stopgap
ahead of a full NLEM (National List of Essential Medicines) / Jan Aushadhi
ingest, which is secondary and does not exist yet. Every entry below was
written by hand and reviewed for internal consistency (see
`tests/test_formulary.py`'s seed-data-integrity tests).

**What the dosing fields mean, and what they do not.** `min_adult_dose` /
`max_adult_dose` / `max_daily_dose` describe a standard, commonly-cited
adult oral dosing range for routine outpatient use -- the kind of range
printed in a national formulary or the WHO Model List of Essential
Medicines. Chosen deliberately conservatively (the lower end of commonly
cited ranges, not the aggressive/maximum end) where a range exists in the
literature. They are a safety *reference range* for CLAUDE.md invariant #3
("refuse rather than guess"): a dose captured from OCR/ASR/the LLM
fallback that falls outside this range is precisely the kind of thing that
should trigger `NeedsHumanConfirmation`. They are NOT a prescribing
recommendation, do not cover pediatric, renal-impairment,
hepatic-impairment, or pregnancy dosing, and never override the actual
prescriber's written/spoken instruction.

**Brand names** (`common_brand_names`) are deliberately sparse: only
included where confidence is high (long-established, widely recognised
Indian brands). An empty tuple was preferred over a guess -- India has
thousands of brand names per generic, region and manufacturer, and a wrong
brand-to-generic mapping is worse than none.

**Tamil/Hindi names** (`tamil_name`, `hindi_name`) are phonetic
transliterations of the generic name (there is usually no native *word*
for a generic drug name, only a rendering of how it is said), written
using standard, widely-seen pharmacy-label transliteration conventions.
They have not been reviewed by a native-speaker pharmacist and should be
before any patient-facing use -- see `docs/ASSUMPTIONS.md`.

Excluded deliberately: anything needing complex/individualized dosing this
seed set cannot represent safely (insulin, warfarin, chemotherapy),
anything withdrawn or restricted in India (ranitidine, withdrawn over NDMA
contamination -- famotidine is included instead as the H2-blocker
alternative).
"""
from __future__ import annotations

from typing import Tuple

from puriyudha.formulary.models import FormularyDrug

SEED_DRUGS: Tuple[FormularyDrug, ...] = (
    # --- Analgesic / antipyretic / NSAID -------------------------------------
    FormularyDrug(
        generic_name="paracetamol",
        display_name="Paracetamol",
        tamil_name="பாராசிட்டமால்",
        hindi_name="पैरासिटामोल",
        category="analgesic-antipyretic",
        forms=("tablet", "syrup"),
        common_strengths=("500 mg", "650 mg", "125 mg/5 ml syrup"),
        dose_unit="mg",
        min_adult_dose=500.0,
        max_adult_dose=1000.0,
        max_daily_dose=4000.0,
        typical_frequency_per_day=(3, 4),
        route="oral",
        common_brand_names=("Dolo", "Crocin"),
    ),
    FormularyDrug(
        generic_name="ibuprofen",
        display_name="Ibuprofen",
        tamil_name="ஐபுப்ரோஃபென்",
        hindi_name="आइबुप्रोफेन",
        category="nsaid",
        forms=("tablet", "syrup"),
        common_strengths=("200 mg", "400 mg", "100 mg/5 ml syrup"),
        dose_unit="mg",
        min_adult_dose=200.0,
        max_adult_dose=400.0,
        max_daily_dose=1200.0,
        typical_frequency_per_day=(3, 4),
        route="oral",
        common_brand_names=("Brufen",),
    ),
    FormularyDrug(
        generic_name="diclofenac",
        display_name="Diclofenac",
        tamil_name="டைக்ளோஃபெனாக்",
        hindi_name="डाइक्लोफेनाक",
        category="nsaid",
        forms=("tablet",),
        common_strengths=("50 mg",),
        dose_unit="mg",
        min_adult_dose=25.0,
        max_adult_dose=50.0,
        max_daily_dose=150.0,
        typical_frequency_per_day=(2, 3),
        route="oral",
        common_brand_names=("Voveran",),
    ),
    FormularyDrug(
        generic_name="aspirin",
        display_name="Aspirin",
        tamil_name="ஆஸ்பிரின்",
        hindi_name="एस्पिरिन",
        category="antiplatelet",
        forms=("tablet",),
        common_strengths=("75 mg", "150 mg"),
        dose_unit="mg",
        min_adult_dose=75.0,
        max_adult_dose=150.0,
        max_daily_dose=150.0,
        typical_frequency_per_day=(1,),
        route="oral",
        common_brand_names=("Ecosprin",),
    ),
    FormularyDrug(
        generic_name="mefenamic acid",
        display_name="Mefenamic Acid",
        tamil_name="மெஃபெனாமிக் அமிலம்",
        hindi_name="मेफेनैमिक एसिड",
        category="nsaid",
        forms=("tablet", "syrup"),
        common_strengths=("250 mg", "500 mg"),
        dose_unit="mg",
        min_adult_dose=250.0,
        max_adult_dose=500.0,
        max_daily_dose=1500.0,
        typical_frequency_per_day=(3,),
        route="oral",
        common_brand_names=("Meftal",),
    ),
    FormularyDrug(
        generic_name="etoricoxib",
        display_name="Etoricoxib",
        tamil_name="எடோரிகாக்சிப்",
        hindi_name="इटोरिकॉक्सिब",
        category="nsaid",
        forms=("tablet",),
        common_strengths=("60 mg", "90 mg", "120 mg"),
        dose_unit="mg",
        min_adult_dose=60.0,
        max_adult_dose=120.0,
        max_daily_dose=120.0,
        typical_frequency_per_day=(1,),
        route="oral",
        common_brand_names=("Nucoxia",),
    ),
    # --- Antibiotics -----------------------------------------------------------
    FormularyDrug(
        generic_name="amoxicillin",
        display_name="Amoxicillin",
        tamil_name="அமோக்ஸிசிலின்",
        hindi_name="एमोक्सिसिलिन",
        category="antibiotic",
        forms=("tablet", "capsule", "syrup"),
        common_strengths=("250 mg", "500 mg", "125 mg/5 ml syrup"),
        dose_unit="mg",
        min_adult_dose=250.0,
        max_adult_dose=500.0,
        max_daily_dose=1500.0,
        typical_frequency_per_day=(3,),
        route="oral",
        common_brand_names=("Novamox",),
    ),
    FormularyDrug(
        generic_name="amoxicillin-clavulanate",
        display_name="Amoxicillin-Clavulanate",
        tamil_name="அமோக்ஸிசிலின்-கிளாவுலனேட்",
        hindi_name="एमोक्सिसिलिन-क्लैवुलैनेट",
        category="antibiotic",
        forms=("tablet", "syrup"),
        common_strengths=("375 mg", "625 mg", "228.5 mg/5 ml syrup"),
        dose_unit="mg",
        min_adult_dose=375.0,
        max_adult_dose=625.0,
        max_daily_dose=1875.0,
        typical_frequency_per_day=(2, 3),
        route="oral",
        common_brand_names=("Augmentin",),
    ),
    FormularyDrug(
        generic_name="azithromycin",
        display_name="Azithromycin",
        tamil_name="அசித்ரோமைசின்",
        hindi_name="एज़िथ्रोमाइसिन",
        category="antibiotic",
        forms=("tablet", "syrup"),
        common_strengths=("250 mg", "500 mg"),
        dose_unit="mg",
        min_adult_dose=250.0,
        max_adult_dose=500.0,
        max_daily_dose=500.0,
        typical_frequency_per_day=(1,),
        route="oral",
        common_brand_names=("Azithral",),
    ),
    FormularyDrug(
        generic_name="ciprofloxacin",
        display_name="Ciprofloxacin",
        tamil_name="சிப்ரோஃப்ளாக்சசின்",
        hindi_name="सिप्रोफ्लोक्सासिन",
        category="antibiotic",
        forms=("tablet",),
        common_strengths=("250 mg", "500 mg", "750 mg"),
        dose_unit="mg",
        min_adult_dose=250.0,
        max_adult_dose=750.0,
        max_daily_dose=1500.0,
        typical_frequency_per_day=(2,),
        route="oral",
        common_brand_names=("Ciplox",),
    ),
    FormularyDrug(
        generic_name="doxycycline",
        display_name="Doxycycline",
        tamil_name="டாக்ஸிசைக்ளின்",
        hindi_name="डॉक्सीसाइक्लिन",
        category="antibiotic",
        forms=("tablet", "capsule"),
        common_strengths=("100 mg",),
        dose_unit="mg",
        min_adult_dose=100.0,
        max_adult_dose=100.0,
        max_daily_dose=200.0,
        typical_frequency_per_day=(1, 2),
        route="oral",
        common_brand_names=("Doxt",),
    ),
    FormularyDrug(
        generic_name="metronidazole",
        display_name="Metronidazole",
        tamil_name="மெட்ரோனிடசோல்",
        hindi_name="मेट्रोनिडाज़ोल",
        category="antibiotic-antiprotozoal",
        forms=("tablet", "syrup"),
        common_strengths=("200 mg", "400 mg"),
        dose_unit="mg",
        min_adult_dose=400.0,
        max_adult_dose=400.0,
        max_daily_dose=1200.0,
        typical_frequency_per_day=(3,),
        route="oral",
        common_brand_names=("Flagyl",),
    ),
    FormularyDrug(
        generic_name="cefixime",
        display_name="Cefixime",
        tamil_name="செஃபிக்ஸிம்",
        hindi_name="सेफिक्साइम",
        category="antibiotic",
        forms=("tablet", "syrup"),
        common_strengths=("100 mg", "200 mg"),
        dose_unit="mg",
        min_adult_dose=200.0,
        max_adult_dose=400.0,
        max_daily_dose=400.0,
        typical_frequency_per_day=(1, 2),
        route="oral",
        common_brand_names=("Taxim-O",),
    ),
    # --- GI ----------------------------------------------------------------------
    FormularyDrug(
        generic_name="omeprazole",
        display_name="Omeprazole",
        tamil_name="ஓமிபிராசோல்",
        hindi_name="ओमेप्राज़ोल",
        category="proton-pump-inhibitor",
        forms=("capsule",),
        common_strengths=("20 mg", "40 mg"),
        dose_unit="mg",
        min_adult_dose=20.0,
        max_adult_dose=40.0,
        max_daily_dose=40.0,
        typical_frequency_per_day=(1,),
        route="oral",
        common_brand_names=("Omez",),
    ),
    FormularyDrug(
        generic_name="pantoprazole",
        display_name="Pantoprazole",
        tamil_name="பான்டோபிராசோல்",
        hindi_name="पैंटोप्राज़ोल",
        category="proton-pump-inhibitor",
        forms=("tablet",),
        common_strengths=("40 mg",),
        dose_unit="mg",
        min_adult_dose=40.0,
        max_adult_dose=80.0,
        max_daily_dose=80.0,
        typical_frequency_per_day=(1, 2),
        route="oral",
        common_brand_names=("Pan-40",),
    ),
    FormularyDrug(
        generic_name="domperidone",
        display_name="Domperidone",
        tamil_name="டோம்பெரிடோன்",
        hindi_name="डॉम्पेरिडोन",
        category="prokinetic-antiemetic",
        forms=("tablet", "syrup"),
        common_strengths=("10 mg",),
        dose_unit="mg",
        min_adult_dose=10.0,
        max_adult_dose=10.0,
        max_daily_dose=30.0,
        typical_frequency_per_day=(3,),
        route="oral",
        common_brand_names=("Domstal",),
    ),
    FormularyDrug(
        generic_name="ondansetron",
        display_name="Ondansetron",
        tamil_name="ஆன்டான்செட்ரான்",
        hindi_name="ऑनडांसेट्रॉन",
        category="antiemetic",
        forms=("tablet",),
        common_strengths=("4 mg", "8 mg"),
        dose_unit="mg",
        min_adult_dose=4.0,
        max_adult_dose=8.0,
        max_daily_dose=24.0,
        typical_frequency_per_day=(2, 3),
        route="oral",
        common_brand_names=("Emeset",),
    ),
    FormularyDrug(
        generic_name="dicyclomine",
        display_name="Dicyclomine",
        tamil_name="டைசைக்ளோமின்",
        hindi_name="डाइसाइक्लोमीन",
        category="antispasmodic",
        forms=("tablet", "syrup"),
        common_strengths=("10 mg", "20 mg"),
        dose_unit="mg",
        min_adult_dose=10.0,
        max_adult_dose=20.0,
        max_daily_dose=80.0,
        typical_frequency_per_day=(3, 4),
        route="oral",
        common_brand_names=("Cyclopam",),
    ),
    # --- Antihistamine / allergy / respiratory --------------------------------
    FormularyDrug(
        generic_name="cetirizine",
        display_name="Cetirizine",
        tamil_name="செட்டிரிசின்",
        hindi_name="सेटिरिज़िन",
        category="antihistamine",
        forms=("tablet", "syrup"),
        common_strengths=("10 mg",),
        dose_unit="mg",
        min_adult_dose=10.0,
        max_adult_dose=10.0,
        max_daily_dose=10.0,
        typical_frequency_per_day=(1,),
        route="oral",
        common_brand_names=(),
    ),
    FormularyDrug(
        generic_name="levocetirizine",
        display_name="Levocetirizine",
        tamil_name="லீவோசெட்டிரிசின்",
        hindi_name="लेवोसेटिरिज़िन",
        category="antihistamine",
        forms=("tablet", "syrup"),
        common_strengths=("5 mg",),
        dose_unit="mg",
        min_adult_dose=5.0,
        max_adult_dose=5.0,
        max_daily_dose=5.0,
        typical_frequency_per_day=(1,),
        route="oral",
        common_brand_names=(),
    ),
    FormularyDrug(
        generic_name="montelukast",
        display_name="Montelukast",
        tamil_name="மான்டிலுகாஸ்ட்",
        hindi_name="मोंटेलुकास्ट",
        category="leukotriene-antagonist",
        forms=("tablet",),
        common_strengths=("10 mg",),
        dose_unit="mg",
        min_adult_dose=10.0,
        max_adult_dose=10.0,
        max_daily_dose=10.0,
        typical_frequency_per_day=(1,),
        route="oral",
        common_brand_names=("Montair",),
    ),
    FormularyDrug(
        generic_name="salbutamol",
        display_name="Salbutamol",
        tamil_name="சால்புடமால்",
        hindi_name="सालबुटामोल",
        category="bronchodilator",
        forms=("tablet", "syrup"),
        common_strengths=("2 mg", "4 mg"),
        dose_unit="mg",
        min_adult_dose=2.0,
        max_adult_dose=4.0,
        max_daily_dose=16.0,
        typical_frequency_per_day=(3, 4),
        route="oral",
        common_brand_names=("Asthalin",),
    ),
    FormularyDrug(
        generic_name="bromhexine",
        display_name="Bromhexine",
        tamil_name="புரோம்ஹெக்ஸின்",
        hindi_name="ब्रोमहेक्सिन",
        category="mucolytic",
        forms=("tablet", "syrup"),
        common_strengths=("8 mg",),
        dose_unit="mg",
        min_adult_dose=8.0,
        max_adult_dose=8.0,
        max_daily_dose=24.0,
        typical_frequency_per_day=(3,),
        route="oral",
        common_brand_names=(),
    ),
    # --- Cardiovascular ----------------------------------------------------------
    FormularyDrug(
        generic_name="amlodipine",
        display_name="Amlodipine",
        tamil_name="அம்லோடிபின்",
        hindi_name="एम्लोडिपिन",
        category="calcium-channel-blocker",
        forms=("tablet",),
        common_strengths=("2.5 mg", "5 mg", "10 mg"),
        dose_unit="mg",
        min_adult_dose=5.0,
        max_adult_dose=10.0,
        max_daily_dose=10.0,
        typical_frequency_per_day=(1,),
        route="oral",
        common_brand_names=("Amlodac",),
    ),
    FormularyDrug(
        generic_name="atenolol",
        display_name="Atenolol",
        tamil_name="அடினொலால்",
        hindi_name="एटेनोलोल",
        category="beta-blocker",
        forms=("tablet",),
        common_strengths=("25 mg", "50 mg", "100 mg"),
        dose_unit="mg",
        min_adult_dose=25.0,
        max_adult_dose=100.0,
        max_daily_dose=100.0,
        typical_frequency_per_day=(1,),
        route="oral",
        common_brand_names=(),
    ),
    FormularyDrug(
        generic_name="losartan",
        display_name="Losartan",
        tamil_name="லோசார்டன்",
        hindi_name="लोसार्टन",
        category="angiotensin-receptor-blocker",
        forms=("tablet",),
        common_strengths=("25 mg", "50 mg", "100 mg"),
        dose_unit="mg",
        min_adult_dose=25.0,
        max_adult_dose=100.0,
        max_daily_dose=100.0,
        typical_frequency_per_day=(1, 2),
        route="oral",
        common_brand_names=("Losar",),
    ),
    FormularyDrug(
        generic_name="telmisartan",
        display_name="Telmisartan",
        tamil_name="டெல்மிசார்டன்",
        hindi_name="टेल्मिसार्टन",
        category="angiotensin-receptor-blocker",
        forms=("tablet",),
        common_strengths=("20 mg", "40 mg", "80 mg"),
        dose_unit="mg",
        min_adult_dose=20.0,
        max_adult_dose=80.0,
        max_daily_dose=80.0,
        typical_frequency_per_day=(1,),
        route="oral",
        common_brand_names=("Telma",),
    ),
    FormularyDrug(
        generic_name="atorvastatin",
        display_name="Atorvastatin",
        tamil_name="அடோர்வாஸ்டேடின்",
        hindi_name="एटोरवास्टेटिन",
        category="statin",
        forms=("tablet",),
        common_strengths=("10 mg", "20 mg", "40 mg"),
        dose_unit="mg",
        min_adult_dose=10.0,
        max_adult_dose=40.0,
        max_daily_dose=40.0,
        typical_frequency_per_day=(1,),
        route="oral",
        common_brand_names=("Atorva",),
    ),
    FormularyDrug(
        generic_name="clopidogrel",
        display_name="Clopidogrel",
        tamil_name="குளோபிடோகிரல்",
        hindi_name="क्लोपिडोग्रेल",
        category="antiplatelet",
        forms=("tablet",),
        common_strengths=("75 mg",),
        dose_unit="mg",
        min_adult_dose=75.0,
        max_adult_dose=75.0,
        max_daily_dose=75.0,
        typical_frequency_per_day=(1,),
        route="oral",
        common_brand_names=("Clopilet",),
    ),
    FormularyDrug(
        generic_name="furosemide",
        display_name="Furosemide",
        tamil_name="ஃபியூரோசைமைடு",
        hindi_name="फ्यूरोसेमाइड",
        category="loop-diuretic",
        forms=("tablet",),
        common_strengths=("20 mg", "40 mg"),
        dose_unit="mg",
        min_adult_dose=20.0,
        max_adult_dose=80.0,
        max_daily_dose=80.0,
        typical_frequency_per_day=(1, 2),
        route="oral",
        common_brand_names=("Lasix",),
    ),
    # --- Diabetes ------------------------------------------------------------------
    FormularyDrug(
        generic_name="metformin",
        display_name="Metformin",
        tamil_name="மெட்ஃபார்மின்",
        hindi_name="मेटफॉर्मिन",
        category="biguanide-antidiabetic",
        forms=("tablet",),
        common_strengths=("500 mg", "850 mg", "1000 mg"),
        dose_unit="mg",
        min_adult_dose=500.0,
        max_adult_dose=1000.0,
        max_daily_dose=2000.0,
        typical_frequency_per_day=(2, 3),
        route="oral",
        common_brand_names=("Glycomet",),
    ),
    FormularyDrug(
        generic_name="glimepiride",
        display_name="Glimepiride",
        tamil_name="கிளிமிபிரைடு",
        hindi_name="ग्लिमेपिराइड",
        category="sulfonylurea-antidiabetic",
        forms=("tablet",),
        common_strengths=("1 mg", "2 mg", "4 mg"),
        dose_unit="mg",
        min_adult_dose=1.0,
        max_adult_dose=4.0,
        max_daily_dose=8.0,
        typical_frequency_per_day=(1,),
        route="oral",
        common_brand_names=("Amaryl",),
    ),
    FormularyDrug(
        generic_name="sitagliptin",
        display_name="Sitagliptin",
        tamil_name="சிடாக்ளிப்டின்",
        hindi_name="सिटाग्लिप्टिन",
        category="dpp4-inhibitor-antidiabetic",
        forms=("tablet",),
        common_strengths=("25 mg", "50 mg", "100 mg"),
        dose_unit="mg",
        min_adult_dose=100.0,
        max_adult_dose=100.0,
        max_daily_dose=100.0,
        typical_frequency_per_day=(1,),
        route="oral",
        common_brand_names=("Januvia",),
    ),
    # --- Thyroid ---------------------------------------------------------------------
    FormularyDrug(
        generic_name="levothyroxine",
        display_name="Levothyroxine",
        tamil_name="லீவோதைராக்ஸின்",
        hindi_name="लेवोथायरोक्सिन",
        category="thyroid-hormone",
        forms=("tablet",),
        common_strengths=("25 mcg", "50 mcg", "100 mcg", "125 mcg"),
        dose_unit="mcg",
        min_adult_dose=25.0,
        max_adult_dose=200.0,
        max_daily_dose=200.0,
        typical_frequency_per_day=(1,),
        route="oral",
        common_brand_names=("Thyronorm",),
    ),
    # --- Vitamins / supplements ---------------------------------------------------
    FormularyDrug(
        generic_name="multivitamin",
        display_name="Multivitamin",
        tamil_name="மல்டிவைட்டமின்",
        hindi_name="मल्टीविटामिन",
        category="supplement",
        forms=("tablet",),
        common_strengths=("standard adult multivitamin",),
        dose_unit="tablet",
        min_adult_dose=1.0,
        max_adult_dose=1.0,
        max_daily_dose=1.0,
        typical_frequency_per_day=(1,),
        route="oral",
        common_brand_names=("Revital",),
    ),
    FormularyDrug(
        generic_name="vitamin b-complex",
        display_name="Vitamin B-Complex",
        tamil_name="வைட்டமின் பி-காம்ப்ளக்ஸ்",
        hindi_name="विटामिन बी-कॉम्प्लेक्स",
        category="supplement",
        forms=("tablet", "syrup"),
        common_strengths=("standard adult B-complex",),
        dose_unit="tablet",
        min_adult_dose=1.0,
        max_adult_dose=1.0,
        max_daily_dose=1.0,
        typical_frequency_per_day=(1,),
        route="oral",
        common_brand_names=("Becosules",),
    ),
    FormularyDrug(
        generic_name="calcium + vitamin d3",
        display_name="Calcium + Vitamin D3",
        tamil_name="கால்சியம் + வைட்டமின் டி3",
        hindi_name="कैल्शियम + विटामिन डी3",
        category="supplement",
        forms=("tablet",),
        common_strengths=("500 mg calcium + 250 IU vitamin D3",),
        dose_unit="tablet",
        min_adult_dose=1.0,
        max_adult_dose=2.0,
        max_daily_dose=2.0,
        typical_frequency_per_day=(1, 2),
        route="oral",
        common_brand_names=("Shelcal",),
    ),
    FormularyDrug(
        generic_name="iron + folic acid",
        display_name="Iron + Folic Acid",
        tamil_name="இரும்பு + ஃபோலிக் அமிலம்",
        hindi_name="आयरन + फोलिक एसिड",
        category="supplement",
        forms=("tablet",),
        common_strengths=("100 mg elemental iron + 0.5 mg folic acid",),
        dose_unit="tablet",
        min_adult_dose=1.0,
        max_adult_dose=1.0,
        max_daily_dose=1.0,
        typical_frequency_per_day=(1,),
        route="oral",
        common_brand_names=("Fefol",),
    ),
    # --- Antiparasitic ---------------------------------------------------------------
    FormularyDrug(
        generic_name="albendazole",
        display_name="Albendazole",
        tamil_name="அல்பென்டசோல்",
        hindi_name="एल्बेंडाज़ोल",
        category="anthelmintic",
        forms=("tablet", "syrup"),
        common_strengths=("400 mg",),
        dose_unit="mg",
        min_adult_dose=400.0,
        max_adult_dose=400.0,
        max_daily_dose=400.0,
        typical_frequency_per_day=(1,),
        route="oral",
        common_brand_names=("Zentel",),
    ),
    # --- H2 blocker (famotidine, not ranitidine -- see module docstring) -------------
    FormularyDrug(
        generic_name="famotidine",
        display_name="Famotidine",
        tamil_name="ஃபாமோடிடின்",
        hindi_name="फैमोटिडीन",
        category="h2-blocker",
        forms=("tablet",),
        common_strengths=("20 mg", "40 mg"),
        dose_unit="mg",
        min_adult_dose=20.0,
        max_adult_dose=40.0,
        max_daily_dose=80.0,
        typical_frequency_per_day=(1, 2),
        route="oral",
        common_brand_names=(),
    ),
)
